### ISSUE TITLE
*328 lua entry thread aborted: runtime error: table overflow

### ISSUE THREAD

**Issue by benboughton1** [timburgess/chickpea#1] opened 2016-10-04 22:49 UTC
```
2016/10/04 18:45:09 [error] 25391#0: *328 lua entry thread aborted: runtime error: table overflow
stack traceback:
coroutine 0:
        [C]: in function 'cdef'
        /home/ben/src/chickpea/serve_image.lua:89: in function </home/ben/src/chickpea/serve_image.lua:1>, client: 121.216.215.163, server: , request: "GET /tile/l8/091080/svi/20160924/13/7496/4780.jpg HTTP/1.1", host: "tileservtest.satamap.com.au:8000", referrer: "http://19-2-dot-satamap-git.appspot.com/mainmap?aoi=091080"
```

Testing out ran into a table overflow issue when I really hammered panning around etc.

**Comment by timburgess** [comment] 2016-10-08 22:32
I'm pretty sure this happens because the C definitions are loaded for each pass through the LuaJIT VM i.e. each request. Thus, eventually the internal table that holds them will overflow. I have made changes in the latest code that hopefully fixes this.

**Comment by benboughton1** [comment] 2016-10-09 10:44
Unfortunately copped this one again tonight. What not especially trying to break it - just panning around normally on 4k wide screen.

**Comment by timburgess** [comment] 2016-10-09 22:11
I’ve been putting the S2A logic in this morning, both into the tileserver and the requisite matching changes in 19-2. The S2A is obviously without path row references. This is easy enough to do in the url validation routine I’ve written as I can just construct the required xml pathname on the fly as the code knows the sat type. As the L8 needs the path row, I’ve gone with a RESTful style of “/“ separating the resources.

There is possibly a way of writing a new regex and nginx location for S2A explicitly but for the purpose of getting things functional asap, I am going to simply assign a value of 999999 for S2A requests for the path row parameter. This will allow me to use the same nginx location directive, from which every things flows from at present.

**Comment by timburgess** [comment] 2016-10-14 23:19
The issue has now been fixed and committed to master. Essentially, you can't use LuaJIT cdef's outside a module as each request will add them to the LuaJIT internal cdef table and thus you eventually get an overflow. 

I've reimplemented all C calls within a new mapnik module. With a single nginx worker, it took about 1800 requests to overflow the table. I've now pulled 14000 tiles in a test on the new code so confident the issue is dealt with.

**Closed as completed by timburgess** 2016-10-14 23:19 UTC
